warningtext1: "&6[Chess] &cYou have already joined the board"
warningtext2: "&6[Chess] &cYou don't have enough"
warningtext3: "&6[Chess] &cYou can only accept to play with the selected bet"
warningtext4: "&c[Chess] &cYou can only cancel from the board you joined"
successtext1: "&6[Chess] &aYou have successfully joined the board"
successtext2: "&6[Chess] &aYou have successfully accepted to play chess"
successtext3: "&6[Chess] &aYou left the board"
hologramtext1: "&6WHITE:&c"
hologramtext2: "&6BLACK:&c"
hologramtext3: "&6BET:&c"
hologramtext4: "&aTime limit:&c"
hologramtext5: "&cmin"
timertext1: "TIMER"
timertext2: "WHITE"
timertext3: "BLACK"
gametext1: "&cYou can't move this figure right now, your &6KING &cis or will be in danger!"
gametext2: "&cThis move is illegal!"
gametext3: "&6CHECK"
gametext4: "&6[Chess] &aPlayer"
gametext5: "&ahas won chess game against player"
gametext6: "&aCHECKMATE"
gametext7: "&cCHECKMATE"
gametext8: "&cNot your turn"
gametext9: "&cyou have to choose to what promote the pawn"
surrendertext1: "&6Click again to confirm surrender"
ratingtext1: "&6[Chess] Player:&c"
ratingtext2: "&6, Rating:&c"
ratingtext3: "&6, Games:&c"
ratingtext4: "&a---TOP 5 Players---"
ratingtext5: "&c[Chess] Player must be online"
kicktext: "&c[Chess] You were kicked off the chess board"

kickafter: 5
enableboardedges: true

