name: MinecraftChess
version: ${project.version}
main: com.gmail.laurynas.pazdrazdis.minecraftpart.minecraftchessmain.MinecraftChessMain
author: Laurynas
api-version: 1.16
commands:
  mchess:
    description: MinecraftChess config command
    usage: /mchess
    permission: minecraftchess.configcommands
  chessratings:
    description: MinecraftChess ratings command
    usage: /chessratings
softdepend: [Hyperverse, Multiverse-Core]
